auto:	          true

highlighter:      rouge
paginate:         1
permalink:        /:categories/:year/:month/:day/:title/

title:            "mayloveless's Blog"
url:              http://wanglingfei.github.io
author:
    name:         wanglingfei
    twitter:      twitter.com
    key:          mayloveless
description:      "未完成"
copyright:        "CopryRight GuoJing 2012-2017 by GitHub and Jekyll"
headdesc:         "Mayloveless的博客"
