auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         2
permalink:        /:categories/:year/:month/:day/:title/

title:            "mayloveless's Blog"
url:              http://wanglingfei.github.io
author:
    name:         wanglingfei
    twitter:      twitter.com
    key:          mayloveless
description:      " "
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"
headdesc:         "Mayloveless的博客"
